resource "network" "main" {
  subnet = "10.0.5.0/24"
}

// Create a Kubernetes cluster using the k3s distribution.
resource "kubernetes_cluster" "k3s" {
  network {
    id = resource.network.main.meta.id
  }
}

// This container is used as an interactive terminal to the Kubernetes cluster.
// It uses the Bitnami kubectl image to provide a command line interface to the cluster.
// The container is configured to use the kubeconfig file generated by the Kubernetes cluster resource.
resource "container" "workstation" {
  image {
    name = "bitnami/kubectl"
  }

  // Override the default entrypoint to use bash instead of kubectl,
  // so the container does not exit immediately.
  entrypoint = ["/bin/bash"]

  network {
    id = resource.network.main.meta.id
  }

  // Mount the kubeconfig file generated by the Kubernetes cluster resource
  // to the container's /root/.kube/config path.
  volume {
    source      = resource.kubernetes_cluster.k3s.kube_config.path
    destination = "/root/.kube/config"
  }

  // Set the KUBECONFIG environment variable to point to the mounted kubeconfig file.
  // This allows kubectl commands to use the kubeconfig file for authentication.
  environment = {
    KUBECONFIG = "/root/.kube/config"
  }
}
